### ISSUE TITLE
Add the fundamental for building NFT Marketplace

### ISSUE THREAD

**Issue by gyuguen** [medibloc/panacea-core#225]
We need to support the marketplace for [cw-721](https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw721-base) and [cw-1155](https://github.com/CosmWasm/cw-plus/tree/main/contracts/cw1155-base).

# Design

* The seller registers the NFT as an asset.
  * If an asset is registered, it is registered in its own collection and exposed.
  * Required to `my_account_address, contract_address, token_id`

## How to trade
There are two ways to trade asset.

### Registered with marketplace and traded.
* The seller may register the assets registered in the collection with the Marketplace and request immediate sales or auction.
  * For immediate sales, we sell it at a specified price.
  * In the case of an auction, it starts at the minimum starting price and is automatically sold to the maximum bidder during the auction time.
  * When registing immediate sales and auctions, you can raise one or more asset in bundle.
  * Buyer can check and purchase the sales list through the marketplace

### Enter the seller's(author) account, view assets, and request a transaction.
* The seller's account has a list of assets owned by the account exposed.
* If an asset is put up for sale, the transaction is possible, bu if not, the buyer may request the sale of the asset.
* Offer prices when requesting sales of assets.
* Seller can sell assets by looking at the sales offer price.

### Reference
https://docs.opensea.io/docs/opensea-sdk
https://docs.onflow.org/cadence/tutorial/06-marketplace-compose/#marketplace-design
https://www.uptickproject.com/

**Comment by youngjoon-lee** [comment]
Let's say that the goal of this issue is having the fundamental for building NFT marketplace, excluding the implementation of the marketplace web UI. 
For example, we may need some smart contracts for trading NFTs. So, let's research how other marketplaces have been built. 
It would be the best If there is any pre-built option that we can use. If not, we can define (or implement) simple smart contracts for trading NFTs.

Let's keep it in mind that it's not urgent to build the marketplace web for now. The goal is having the strategy how to build the marketplace whenever we really need.

**Comment by youngjoon-lee** [comment]
I'm closing this issue since the official `x/nft/ module is being developed in the Cosmos SDK. That will be also IBC-compatible and will be used in many Cosmos-based NFT marketplace.
