### ISSUE TITLE
검증자는 처음입니다..

### ISSUE THREAD

**Issue by easynew** [medibloc/panacea-core#246]
메디블록 validator에 가입하고 싶어서 몇 일 동안을 여러 번에 걸쳐 시도해 보았는데 성공할 수 없었습니다.
메디블록 가이드나 코스모스 가이드, 텐더민트 가이드 등 여러 가이드를 살펴보았지만 도통 알 수가 없네요.

1. 다른 곳을 보면 faucet 같은 곳에서도 작업을 하는 것 같던데 혹시 파나시어 검증자를 신청하는 절차가 있나요?
2. 일단 정상적으로 작동되는 지는 모르겠지만 $HOME에 설치를 하여 panacead start 명령어는 작동을 시켰습니다. 헌데 validator 설정과정을 알기가 어렵습니다. 자세한 순서를 알려주셨으면 합니다.
3. panacead version --long 명령을 실행하였을 때 server_name이 \<appd\>라고 표시됩니다. 정상적인 것인지요?
4. panacead query account account_panacea 명령어 수행시 rpc, code, key 에러가 발생합니다. 어떻게 해결해야 하나요? 혹은 이 경우는 파나시어 주소로 MED 코인을 입금하는 하는 작업인가요?

업무로 바쁘신 줄은 알지만 메디블록에 관심을 갖고 있는 한 사람의 궁금증을 해결해 주는 것도 시간 낭비는 아니라고 생각됩니다. 

부디 빠르고 자세한 답변 기다리겠습니다.
또는 감사하게도 보내주실 자료가 있다면 doidao@hanmail.net으로 부탁 드립니다.

**Comment by gyuguen** [comment]
Hi. Please understand that all answers are in English.

We operate the mainnet and testnet.
Mainnet is a chain in which MED coins traded on the actual exchange(Upbit, Korbit, Bittrex, etc..) are operated, and Testnet is used for testing purposes.
Faucet is usually used to get coins for testing purposes on the Testnet.

If you want to participate as a validator, Please refer to the following guide.
1. You need a server to participate in the validator node.([minimum spec](https://medibloc.gitbook.io/panacea-core/guide/join-the-network#choose-the-instance-type))
2. You need to [install](https://medibloc.gitbook.io/panacea-core/guide/installation#install-the-panacead) panacead. 
3. [Setup](https://medibloc.gitbook.io/panacea-core/guide/join-the-network#setup-a-new-node) a new node
4. [Copy the Genesis file](https://medibloc.gitbook.io/panacea-core/guide/join-the-network#setup-a-new-node)
5. [Configure Persistent Peers](https://medibloc.gitbook.io/panacea-core/guide/join-the-network#configure-persistent-peers)
6. [Run a Full Node](https://medibloc.gitbook.io/panacea-core/guide/join-the-network#run-a-full-node). However, it is recommended to use the [Background Process](https://medibloc.gitbook.io/panacea-core/guide/join-the-network#background-process) for automatic restart.
7. [Create your validator](https://medibloc.gitbook.io/panacea-core/guide/interaction-with-the-network-cli#staking)
8. You can find your node [here](https://www.mintscan.io/medibloc/validators)

The server configuration recommends [Sentry architecture](https://docs.tendermint.com/master/nodes/validators.html#setting-up-a-validator) to prevent DDos. 

The validator has a lot of responsibility instead of taking the reward.
* In order to act as a validator, the staking value must be high. It's possible in small quantities because the validator hasn't reached its maximum yet, but you may have to have more staking value in the future.
* The node should not be down. If it goes down, the funds deposited will be slashing.
* You should also participate in governance activities. You must review the registered proposal and vote.
* You need to participate in software upgrade normally. Otherwise, the node will be down and slashed.

In addition, it is not easy to participate without expertise in validators.
Since validator require multiple responsibilities and incidental costs (server maintenance costs), it is recommended that ordinary users participate as delegators.
If you participate as a delegate, you can participate in governance with get reward excluding a small fee.

**Comment by gyuguen** [comment]
If you participate as a validator, we recommend to participate in the `Mainnet` after conducting sufficient tests on the `Testnet`
