### ISSUE TITLE
Add a guide to apply the validator's description.

### ISSUE THREAD

**Issue by gyuguen** [medibloc/panacea-core#247]
## BackGround
* There is no explanation of the validator description in our guide

## Goal
* We need to guide validator participating in Panacea on how to modify the validator description
* Refer to [Hub's](https://hub.cosmos.network/main/validators/validator-setup.html#edit-validator-description) guide.
* We also need to add a guide for image support displayed on MintScan and Cosmostation's mobile wallet.
  * refer: https://github.com/cosmostation/cosmostation_token_resource

**Comment by youngjoon-lee** [comment]
Currently, all guides for creating a validator are in the `Interaction with the network: CLI` category, but I think we should have a separated category only for validators as the Cosmos Hub doc. I'll think about how to reorganize categories. As I remember, the Osmosis doc has the guide for promoting a full node to a validator node (right next to the full node setup guide). It would be good enough because people usually setup a full node first (according to the `Join the Network` guide) and promote it into a validator node later.

**Comment by gyuguen** [comment]
That's right. I agree.
It would be nice to modify the document configuration.
