### ISSUE TITLE
Update a Deal Status in Endblocker

### ISSUE THREAD

**Issue by inchori** [medibloc/panacea-core#414]
Update a Deal Status in `EndBlocker`.
- When the deal is ready or being started, the status should be `ACTIVE`.
- When the deal is completed, the status should be `COMPLETED`.

**Comment by audtlr24** [comment]
In the process of processing the vote, it would be better to update the deal status and check the sale in `verifiableCid vote`.
- In the case of exceeding `maxNumData` due to multiple processing at the same time, it is necessary to think about how to handle it.
- Only votes that do not exceed `maxNumData` are added to the `dataDelivery Queue`.
